### ISSUE TITLE
[request] section labels

### ISSUE THREAD

**Issue by antis81** [sasq64/badass#11]
Can't a section also define a (global) label?

```asm
!section "math", start=$1000
math:  ; <-- redundant
  .func1: !fill 256, <some-function>
  .func2: !fill 256, <some-other-function>
  … 
```

Also a `NoLabel=true` option could be useful to disable the feature.

**EDIT**: Further it may be a good idea that labels become global to a section. Given the above example that means:

```asm
!section "math", start=$1000
  func1: !fill 256, <some-function>           ; <-- call: math.func1
  func2: !fill 256, <some-other-function>     ; <-- call: math.func2
  …
```

**Comment by sasq64** [comment]
I think local labels to section is both hard to do (since they act as global, non-dot within the section and dotted outside) and surprising, since in other assemblers a global label is global regardless of which section it's in.

Auto defining symbols for sections is useful. Both start, end, size and pc actually, so you have labels to reference when copying a relocated section to it's correct place.
